services:
    mage:
        image: mageai/mageai
        stdin_open: true
        tty: true
        ports:
            - "6789:6789"
        volumes:
            - ./:/home/src
        entrypoint: ["/app/run_app.sh"]
        command: ["mage", "start", "data"]
        working_dir: /home/src
        depends_on:
            - postgres
        environment:
            - DATABASE_URL=postgresql://admin:admin@postgres:5432/fibook_db
    postgres:
        image: postgres:14
        restart: always
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=fibook_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    api:
        build:
            context: ./api
        volumes:
            - ./api:/app
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        environment:
            - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://admin:admin@postgres:5432/fibook_db
            - SECRET_KEY=secret
    ui:
        build:
            context: ./ui
        volumes:
            - ./ui:/app
        ports:
            - "3000:3000"
        depends_on:
            - api
        environment:
            - VITE_API_BASE_URL=http://localhost:8000/api/v1

volumes:
    postgres_data:
